name: CI

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  lint-and-test:
    strategy:
      matrix:
        node: ["14.16.0", "15.x"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    env:
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
      TREASURY_PRIV_KEY: ${{ secrets.TREASURY_PRIV_KEY }}
      SECOND_ACC_PRIV_KEY: ${{ secrets.SECOND_ACC_PRIV_KEY }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install -g yarn
 
      - run: yarn install --frozen-lockfile --ignore-scripts

      - run: yarn lint
      - run: yarn test
